# Project flavors

# Target hardware
TARGET=zoul
BOARD=firefly-reva

# Contiki network configuration
MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET

# PROJECT_SOURCEFILES += blink-led.c

all: transmitter receiver

CONTIKI = ../contiki-ng
include $(CONTIKI)/Makefile.include